// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RoroBARREL.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class HANToolBoxXMLGenerator : HANToolBoxXMLGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"<?xml version=""1.0"" encoding=""UTF-8""?>

<XMBML version=""1.0"">
<View id=""han_toolbox_xmb_main""> 
		<Attributes> 
			<Table key=""han_main"">
				<Pair key=""icon_rsc""><String>tex_album_icon</String></Pair>
				<Pair key=""icon_notation""><String>WNT_XmbItemAlbum</String></Pair>
				<Pair key=""title""><String>★ HAN Toolbox</String></Pair>
				<Pair key=""info""><String>The Unofficial Xploit Companion</String></Pair>
				<Pair key=""ingame""><String>disable</String></Pair>
			</Table>
		</Attributes>
			<Items>
			<Query 
				class=""type:x-xmb/folder-pixmap""
				key=""han_main""
				attr=""han_main""
				src=""#han_main_items""/>
			</Items>
		</View>
		
		<View id=""han_main_items""> 
		<Attributes> 
			<Table key=""han_reboot_soft"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/reboot.png</String></Pair>
				<Pair key=""title""><String>Soft Reboot</String></Pair>
				<Pair key=""info""><String>Restart Console</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 35 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/syscalls/soft_reboot.html</String></Pair>
			</Table>
			<Table key=""han_enabler_auto_main"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>HAN Enabler</String></Pair>
				<Pair key=""info""><String>Enable Custom Signed Packages and Licenses</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 42 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write("/han/han_enabler_auto.html</String></Pair>\r\n\t\t\t</Table>\r\n\t\t\t<Table key=\"han_funct" +
                    "ions\">\r\n\t\t\t\t<Pair key=\"icon_rsc\"><String>tex_album_icon</String></Pair>\r\n\t\t\t\t<Pa" +
                    "ir key=\"title\"><String>HAN Functions</String></Pair>\r\n\t\t\t\t<Pair key=\"info\"><Stri" +
                    "ng>Autorun HAN Functions for OFW/CFW Consoles</String></Pair>\r\n\t\t\t</Table>\r\n\t\t\t<" +
                    "Table key=\"han_functions_dex\">\r\n\t\t\t\t<Pair key=\"icon_rsc\"><String>tex_album_icon<" +
                    "/String></Pair>\r\n\t\t\t\t<Pair key=\"title\"><String>HAN Functions (DEX)</String></Pai" +
                    "r>\r\n\t\t\t\t<Pair key=\"info\"><String>Autorun HAN Functions for DEX Firmware</String>" +
                    "</Pair>\r\n\t\t\t</Table>\r\n\t\t\t<Table key=\"han_functions_legacy\">\r\n\t\t\t\t<Pair key=\"icon" +
                    "_rsc\"><String>tex_album_icon</String></Pair>\r\n\t\t\t\t<Pair key=\"title\"><String>HAN " +
                    "Functions (Legacy)</String></Pair>\r\n\t\t\t\t<Pair key=\"info\"><String>Original Non-Au" +
                    "to HAN Functions for OFW/CFW Consoles</String></Pair>\r\n\t\t\t</Table>\r\n\t\t\t<Table ke" +
                    "y=\"han_file_browser\">\r\n\t\t\t\t<Pair key=\"icon_rsc\"><String>tex_album_icon</String><" +
                    "/Pair>\r\n\t\t\t\t<Pair key=\"title\"><String>File Explorer</String></Pair>\r\n\t\t\t\t<Pair k" +
                    "ey=\"info\"><String>Browse Complete File System and Delete Files (Be Careful)</Str" +
                    "ing></Pair>\r\n\t\t\t</Table>\r\n\t\t\t<Table key=\"pkg_linker\">\r\n\t\t\t\t<Pair key=\"icon\"><Str" +
                    "ing>/dev_hdd0/game/HANTOOLBX/USRDIR/package.png</String></Pair>\r\n\t\t\t\t<Pair key=\"" +
                    "title\"><String>Install Packages From Webserver</String></Pair>\r\n\t\t\t\t<Pair key=\"i" +
                    "nfo\"><String>Run a Server on PC to Download and Install Packages</String></Pair>" +
                    "\r\n\t\t\t</Table>\r\n\t\t\t<Table key=\"han_toolbox_setup\">\r\n\t\t\t\t<Pair key=\"icon\"><String>" +
                    "/dev_hdd0/game/HANTOOLBX/USRDIR/setup.png</String></Pair>\r\n\t\t\t\t<Pair key=\"title\"" +
                    "><String>Toolbox Settings</String></Pair>\r\n\t\t\t\t<Pair key=\"info\"><String>Version " +
                    "info, Support, Update</String></Pair>\r\n\t\t\t</Table>\r\n\t\t</Attributes>\r\n\t\t\t<Items>\r" +
                    "\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_reboot_soft\"\r\n\t\t" +
                    "\t\tattr=\"han_reboot_soft\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module-actio" +
                    "n\"\r\n\t\t\t\tkey=\"han_enabler_auto_main\"\r\n\t\t\t\tattr=\"han_enabler_auto_main\"\r\n\t\t\t\t/>\r\n\t" +
                    "\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/folder-pixmap\" \r\n\t\t\t\tkey=\"han_functions\" \r\n\t\t\t\t" +
                    "attr=\"han_functions\"\r\n\t\t\t\tsrc=\"#han_functions_main\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tcla" +
                    "ss=\"type:x-xmb/folder-pixmap\" \r\n\t\t\t\tkey=\"han_functions_dex\" \r\n\t\t\t\tattr=\"han_func" +
                    "tions_dex\"\r\n\t\t\t\tsrc=\"#han_functions_dex_main\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"ty" +
                    "pe:x-xmb/folder-pixmap\" \r\n\t\t\t\tkey=\"han_functions_legacy\" \r\n\t\t\t\tattr=\"han_functio" +
                    "ns_legacy\"\r\n\t\t\t\tsrc=\"#han_functions_legacy_main\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=" +
                    "\"type:x-xmb/folder-pixmap\" \r\n\t\t\t\tkey=\"han_file_browser\"\r\n\t\t\t\tattr=\"han_file_brow" +
                    "ser\" \t\t\t\t\r\n\t\t\t\tsrc=\"host://localhost/\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xm" +
                    "b/folder-pixmap\" \r\n\t\t\t\tkey=\"pkg_linker\" \r\n\t\t\t\tattr=\"pkg_linker\"\r\n\t\t\t\tsrc=\"xmb://" +
                    "localhost/dev_hdd0/game/PKGLINKER/USRDIR/package_link.xml#pkg_items\"\r\n\t\t\t\t/>\r\n\t\t" +
                    "\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/folder-pixmap\" \r\n\t\t\t\tkey=\"han_toolbox_setup\" \r\n\t" +
                    "\t\t\tattr=\"han_toolbox_setup\"\r\n\t\t\t\tsrc=\"#han_toolbox_setup_main\"\r\n\t\t\t\t/>\r\n\t\t\t</Ite" +
                    "ms>\r\n\t\t</View>\r\n\t\t\r\n\t\t<View id=\"han_functions_main\"> \r\n\t\t<Attributes> \r\n\t\t\t<Tabl" +
                    "e key=\"han_reboot_soft_auto\">\r\n\t\t\t\t<Pair key=\"icon\"><String>/dev_hdd0/game/HANTO" +
                    "OLBX/USRDIR/reboot.png</String></Pair>\r\n\t\t\t\t<Pair key=\"title\"><String>Soft Reboo" +
                    "t</String></Pair>\r\n\t\t\t\t<Pair key=\"info\"><String>Restart Console</String></Pair>\r" +
                    "\n\t\t\t\t<Pair key=\"module_name\"><String>webrender_plugin</String></Pair>\r\n\t\t\t\t<Pair" +
                    " key=\"module_action\"><String>http://");
            
            #line 132 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/syscalls/soft_reboot.html</String></Pair>
			</Table>
			<Table key=""han_reboot_hard_auto"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/reboot.png</String></Pair>
				<Pair key=""title""><String>Hard Reboot</String></Pair>
				<Pair key=""info""><String>Restart Console</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 139 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/syscalls/hard_reboot.html</String></Pair>
			</Table>
			<Table key=""han_shutdown_auto"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/shutdown.png</String></Pair>
				<Pair key=""title""><String>Shutdown</String></Pair>
				<Pair key=""info""><String>Turn Off Console</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 146 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/syscalls/power_down.html</String></Pair>
			</Table>
			<Table key=""han_enabler_auto"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>HAN Enabler</String></Pair>
				<Pair key=""info""><String>Enable Custom Signed Packages and Licenses</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 153 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/han/han_enabler_auto.html</String></Pair>
			</Table>
			<Table key=""han_installer_auto"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>HAN Installer</String></Pair>
				<Pair key=""info""><String>Enable Package Manager</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 160 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/han/han_installer_auto.html</String></Pair>
			</Table>
			<Table key=""han_license_dumper_auto"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>License Dumper</String></Pair>
				<Pair key=""info""><String>Dump Activation Data (act.dat/idps)</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 167 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/han/actidps_dumper_auto.html</String></Pair>
			</Table>
			<Table key=""han_injector_auto"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>Injector</String></Pair>
				<Pair key=""info""><String>Auto Running Injector Xploit Only Useful For act.dat</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 174 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/han/injecter_auto</String></Pair>
			</Table>
			<Table key=""han_debug_auto"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>Debug Package Enabler</String></Pair>
				<Pair key=""info""><String>For Modifed Retail Packages Only</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 181 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/han/dbgpkg_enabler_auto.html</String></Pair>
			</Table>
			<Table key=""han_mount_usb_as_bd"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>Mount USB as BDVD</String></Pair>
				<Pair key=""info""><String>Redirect dev_usb000 to dev_bdvd</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 188 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write("/syscalls/mount_usb000_as_bdvd.html</String></Pair>\r\n\t\t\t</Table>\r\n\t\t</Attributes>" +
                    "\r\n\t\t\t<Items>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_reb" +
                    "oot_soft_auto\"\r\n\t\t\t\tattr=\"han_reboot_soft_auto\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"" +
                    "type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_reboot_hard_auto\"\r\n\t\t\t\tattr=\"han_reboot_" +
                    "hard_auto\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"h" +
                    "an_shutdown_auto\"\r\n\t\t\t\tattr=\"han_shutdown_auto\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"" +
                    "type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_enabler_auto\"\r\n\t\t\t\tattr=\"han_enabler_aut" +
                    "o\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_insta" +
                    "ller_auto\"\r\n\t\t\t\tattr=\"han_installer_auto\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x" +
                    "-xmb/module-action\"\r\n\t\t\t\tkey=\"han_license_dumper_auto\"\r\n\t\t\t\tattr=\"han_license_du" +
                    "mper_auto\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"h" +
                    "an_injector_auto\"\r\n\t\t\t\tattr=\"han_injector_auto\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"" +
                    "type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_debug_auto\"\r\n\t\t\t\tattr=\"han_debug_auto\"\r\n" +
                    "\t\t\t\t/>\r\n\t\t\t<!-- <Query \r\n\t\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_moun" +
                    "t_usb_as_bd\"\r\n\t\t\t\tattr=\"han_mount_usb_as_bd\"\r\n\t\t\t\t/> -->\r\n\t\t\t</Items>\r\n\t\t</View>" +
                    "\r\n\t\t\r\n\t\t<View id=\"han_functions_dex_main\"> \r\n\t\t<Attributes> \r\n\t\t\t<Table key=\"han" +
                    "_reboot_soft_auto_dex\">\r\n\t\t\t\t<Pair key=\"icon\"><String>/dev_hdd0/game/HANTOOLBX/U" +
                    "SRDIR/reboot.png</String></Pair>\r\n\t\t\t\t<Pair key=\"title\"><String>Soft Reboot</Str" +
                    "ing></Pair>\r\n\t\t\t\t<Pair key=\"info\"><String>Restart Console</String></Pair>\r\n\t\t\t\t<" +
                    "Pair key=\"module_name\"><String>webrender_plugin</String></Pair>\r\n\t\t\t\t<Pair key=\"" +
                    "module_action\"><String>http://");
            
            #line 247 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/syscalls/soft_reboot_dex.html</String></Pair>
			</Table>
			<Table key=""han_reboot_hard_auto_dex"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/reboot.png</String></Pair>
				<Pair key=""title""><String>Hard Reboot</String></Pair>
				<Pair key=""info""><String>Restart Console</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 254 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/syscalls/hard_reboot_dex.html</String></Pair>
			</Table>
			<Table key=""han_shutdown_auto_dex"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/shutdown.png</String></Pair>
				<Pair key=""title""><String>Shutdown</String></Pair>
				<Pair key=""info""><String>Turn Off Console</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 261 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/syscalls/power_down_dex.html</String></Pair>
			</Table>
			<Table key=""han_enabler_auto_dex"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>HAN Enabler</String></Pair>
				<Pair key=""info""><String>Enable Custom Signed Packages and Licenses</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 268 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/han/han_enabler_auto_dex.html</String></Pair>
			</Table>
			<Table key=""han_installer_auto_dex"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>HAN Installer</String></Pair>
				<Pair key=""info""><String>Enable Package Manager</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 275 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/han/han_installer_auto_dex.html</String></Pair>
			</Table>
			<Table key=""han_license_dumper_auto_dex"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>License Dumper</String></Pair>
				<Pair key=""info""><String>Dump Activation Data (act.dat/idps)</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 282 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/han/actidps_dumper_auto_dex.html</String></Pair>
			</Table>
			<Table key=""han_injector_auto_dex"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>License Injector</String></Pair>
				<Pair key=""info""><String>Inject Custom Signed Activation Data (act.dat/rif)</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 289 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/han/actrif_copier_auto_dex.html</String></Pair>
			</Table>
			<Table key=""han_debug_auto_dex"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>Debug Package Enabler</String></Pair>
				<Pair key=""info""><String>For Modifed Retail Packages Only</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 296 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/han/dbgpkg_enabler_auto_dex.html</String></Pair>
			</Table>
			<Table key=""han_mount_usb_as_bd_dex"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>Mount USB as BDVD</String></Pair>
				<Pair key=""info""><String>Redirect dev_usb000 to dev_bdvd</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 303 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write("/syscalls/mount_usb000_as_bdvd_dex.html</String></Pair>\r\n\t\t\t</Table>\r\n\t\t</Attribu" +
                    "tes>\r\n\t\t\t<Items>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han" +
                    "_reboot_soft_auto_dex\"\r\n\t\t\t\tattr=\"han_reboot_soft_auto_dex\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r" +
                    "\n\t\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_reboot_hard_auto_dex\"\r\n\t\t\t\ta" +
                    "ttr=\"han_reboot_hard_auto_dex\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module" +
                    "-action\"\r\n\t\t\t\tkey=\"han_shutdown_auto_dex\"\r\n\t\t\t\tattr=\"han_shutdown_auto_dex\"\r\n\t\t\t" +
                    "\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_enabler_auto" +
                    "_dex\"\r\n\t\t\t\tattr=\"han_enabler_auto_dex\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xm" +
                    "b/module-action\"\r\n\t\t\t\tkey=\"han_installer_auto_dex\"\r\n\t\t\t\tattr=\"han_installer_auto" +
                    "_dex\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_li" +
                    "cense_dumper_auto_dex\"\r\n\t\t\t\tattr=\"han_license_dumper_auto_dex\"\r\n\t\t\t\t/>\r\n\t\t\t<Quer" +
                    "y \r\n\t\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_injector_auto_dex\"\r\n\t\t\t\ta" +
                    "ttr=\"han_injector_auto_dex\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module-ac" +
                    "tion\"\r\n\t\t\t\tkey=\"han_debug_auto_dex\"\r\n\t\t\t\tattr=\"han_debug_auto_dex\"\r\n\t\t\t\t/>\r\n\t\t<!" +
                    "--\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_mount_usb_as_bd_d" +
                    "ex\"\r\n\t\t\t\tattr=\"han_mount_usb_as_bd_dex\"\r\n\t\t\t\t/> -->\r\n\t\t\t</Items>\r\n\t\t</View>\r\n\t\t\r" +
                    "\n\t\t<View id=\"han_functions_legacy_main\"> \r\n\t\t<Attributes> \r\n\t\t\t<Table key=\"han_i" +
                    "nstaller\">\r\n\t\t\t\t<Pair key=\"icon\"><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png" +
                    "</String></Pair>\r\n\t\t\t\t<Pair key=\"title\"><String>HAN Installer</String></Pair>\r\n\t" +
                    "\t\t\t<Pair key=\"info\"><String>Enable Package Manager</String></Pair>\r\n\t\t\t\t<Pair ke" +
                    "y=\"module_name\"><String>webrender_plugin</String></Pair>\r\n\t\t\t\t<Pair key=\"module_" +
                    "action\"><String>http://");
            
            #line 362 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/han/han_installer.html</String></Pair>
			</Table>
			<Table key=""han_enabler"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>HAN Enabler</String></Pair>
				<Pair key=""info""><String>Enable Custom Signed Package and License</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 369 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/han/han_enabler.html</String></Pair>
			</Table>
			<Table key=""han_license_dumper"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>License Dumper</String></Pair>
				<Pair key=""info""><String>Dump Activation Data (act.dat+idps)</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 376 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/han/actidps_dumper.html</String></Pair>
			</Table>
			<Table key=""han_injector"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>License Injector</String></Pair>
				<Pair key=""info""><String>Inject Custom Signed Activation Data (act.dat+rif)</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 383 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write(@"/han/injecter</String></Pair>
			</Table>
			<Table key=""han_debug"">
				<Pair key=""icon""><String>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>
				<Pair key=""title""><String>Debug Package Enabler</String></Pair>
				<Pair key=""info""><String>For Modifed Retail Packages Only</String></Pair>
				<Pair key=""module_name""><String>webrender_plugin</String></Pair>
				<Pair key=""module_action""><String>http://");
            
            #line 390 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Host));
            
            #line default
            #line hidden
            this.Write("/han/dbgpkg_enabler.html</String></Pair>\r\n\t\t\t</Table>\r\n\t\t</Attributes>\r\n\t\t\t<Items" +
                    ">\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_installer\"\r\n\t\t" +
                    "\t\tattr=\"han_installer\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module-action\"" +
                    "\r\n\t\t\t\tkey=\"han_enabler\"\r\n\t\t\t\tattr=\"han_enabler\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"" +
                    "type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_license_dumper\"\r\n\t\t\t\tattr=\"han_license_d" +
                    "umper\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_i" +
                    "njector\"\r\n\t\t\t\tattr=\"han_injector\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/mod" +
                    "ule-action\"\r\n\t\t\t\tkey=\"han_debug\"\r\n\t\t\t\tattr=\"han_debug\"\r\n\t\t\t\t/>\r\n\t\t\t</Items>\r\n\t\t<" +
                    "/View>\r\n\t\t\r\n\t\t<View id=\"han_toolbox_setup_main\"> \r\n\t\t<Attributes> \r\n\t\t\t<Table ke" +
                    "y=\"han_toolbox_update\">\r\n\t\t\t\t<Pair key=\"icon\"><String>/dev_hdd0/game/HANTOOLBX/U" +
                    "SRDIR/update.png</String></Pair>\r\n\t\t\t\t<Pair key=\"title\"><String>Update Toolbox</" +
                    "String></Pair>\r\n\t\t\t\t<Pair key=\"info\"><String>Download Latest Toolbox Package</St" +
                    "ring></Pair>\r\n\t\t\t</Table>\r\n\t\t\t<Table key=\"han_support\">\r\n\t\t\t\t<Pair key=\"icon\"><S" +
                    "tring>/dev_hdd0/game/HANTOOLBX/USRDIR/web.png</String></Pair>\r\n\t\t\t\t<Pair key=\"ti" +
                    "tle\"><String>Support Forum</String></Pair>\r\n\t\t\t\t<Pair key=\"info\"><String>Visit t" +
                    "he PSX-Place Xploit 3.0 Thread</String></Pair>\r\n\t\t\t\t<Pair key=\"module_name\"><Str" +
                    "ing>webrender_plugin</String></Pair>\r\n\t\t\t\t<Pair key=\"module_action\"><String>http" +
                    "://www.psx-place.com/threads/ps3xploit-tools-v3-0-han-released-non-cfw-compatibl" +
                    "e-slim-superslim-models.16672/</String></Pair>\r\n\t\t\t</Table>\r\n\t\t\t<Table key=\"han_" +
                    "toolbox_about\">\r\n\t\t\t\t<Pair key=\"icon\"><String>/dev_hdd0/game/HANTOOLBX/USRDIR/ab" +
                    "out.png</String></Pair>\r\n\t\t\t\t<Pair key=\"title\"><String>Version: 0.3</String></Pa" +
                    "ir>\r\n\t\t\t\t<Pair key=\"info\"><String>By DeViL303 and Pink1 (Massive Thanks to Team " +
                    "PS3Xploit)</String></Pair>\r\n\t\t\t</Table>\r\n\t\t</Attributes>\r\n\t\t\t<Items>\r\n\t\t\t<Query " +
                    "\r\n\t\t\t\tclass=\"type:x-xmb/folder-pixmap\" \r\n\t\t\t\tkey=\"han_toolbox_update\" \r\n\t\t\t\tattr" +
                    "=\"han_toolbox_update\"\r\n\t\t\t\tsrc=\"#han_toolbox_update_main\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t" +
                    "\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_support\"\r\n\t\t\t\tattr=\"han_suppor" +
                    "t\"\r\n\t\t\t\t/>\r\n\t\t\t<Query \r\n\t\t\t\tclass=\"type:x-xmb/module-action\"\r\n\t\t\t\tkey=\"han_toolb" +
                    "ox_about\"\r\n\t\t\t\tattr=\"han_toolbox_about\"\r\n\t\t\t\t/>\r\n\t\t\t</Items>\r\n\t\t</View>\r\n\t\t\r\n\t\t<" +
                    "View id=\"han_toolbox_update_main\">\r\n\t\t<Attributes>\r\n\t\t\t<Table key=\"han_toolbox_u" +
                    "pdate_item\">\r\n\t\t\t\t<Pair key=\"info\"><String>net_package_install</String></Pair>\r\n" +
                    "\t\t\t\t<Pair key=\"pkg_src\"><String>http://dl.dropboxusercontent.com/s/ylj6q7io9egvp" +
                    "bw/Latest_HAN_Toolbox.pkg</String></Pair>\r\n\t\t\t\t<Pair key=\"pkg_src_qa\"><String>ht" +
                    "tp://dl.dropboxusercontent.com/s/ylj6q7io9egvpbw/Latest_HAN_Toolbox.pkg</String>" +
                    "</Pair>\r\n\t\t\t\t<Pair key=\"content_name\"><String>pkg_install_pc</String></Pair>\r\n\t\t" +
                    "\t\t<Pair key=\"content_id\"><String>UP0100-HANTOOLBX_00-PINK1000DEVIL303</String></" +
                    "Pair>\r\n\t\t\t\t<Pair key=\"prod_pict_path\"><String>/dev_hdd0/game/HANTOOLBX/USRDIR/up" +
                    "date.png</String></Pair>\r\n \t\t\t</Table> \r\n\t\t</Attributes> \r\n\t\t\t<Items>\r\n\t\t\t<Item " +
                    "class=\"type:x-xmb/xmlnpsignup\" key=\"han_toolbox_update_item\" attr=\"han_toolbox_u" +
                    "pdate_item\"/>\r\n\t\t</Items> \r\n\t\t</View> \r\n\t\t\r\n\t\t</XMBML>\r\n\t\t\r\n\t\t");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 480 "C:\Users\sifir\source\repos\RoroBARREL\RoroBARREL\Templates\HANToolBoxXMLGenerator.tt"
 public String Host; 
        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class HANToolBoxXMLGeneratorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
